#ifndef NETWORK_H
#define NETWORK_H
#include <map>
#include "ISocket.h"
#include "CircularBuffer.h"
#include "MySocket.h"

namespace Network {
class Network
{

public:
    Network(unsigned int readCirbufSize = 4096, unsigned int writeCirbufSize = 4096);
    Network(MySocket *sock, unsigned int readCirbufSize = 4096, unsigned int writeCirbufSize = 4096);
    CircularBuffer *    getReadBuffer();
    CircularBuffer *    getWriteBuffer();
    MySocket *          getSocket();
    void                setSocket(MySocket *sock);
    std::string const & getName() const;
    void                setName(std::string const &);

    /*!! in case of client socket in server application,
    you can have the server socket by this way

        will return null on client based network (is the network is not generated by a server
    **/
    Network    *   getRemoteNetwork() const;
    void                setRemoteNetwork(Network *);

protected:
    std::string         _name;
    MySocket *    _socket;
    CircularBuffer      _readBuf;
    CircularBuffer      _writeBuf;
    Network    *_net;
};
}
#endif // NETWORK_H
